### ISSUE TITLE
About trajectory planning/ motion planning part for robosuite

### ISSUE THREAD

**Issue by YunchuZhang** [ARISE-Initiative/robosuite#110]
Hi there,
Thanks for you guys the great work!
I am wondering if there has any path planning part for this simulator, I mean given start and end position.
Or it need manually tune with the IK controller/from demo?

**Comment by cremebrule** [comment]
We do provide the low-level controllers (in both joint and end-effector space) that convert desired actions into raw torque commands, but long-horizon trajectory planning is generally done at the policy-level, which is outside the scope of robosuite.

You could extend the IK (or OSC) class to suit your needs, but we would recommend against doing that since that is overloading the controller functionality and abusing its original purpose.

I'll close this issue for now, but feel free to reopen it or post another issue if you have further questions regarding our controller classes or usage.

Hope that helps!
