### ISSUE TITLE
How to adjust size and position of the object loaded by xml file?

### ISSUE THREAD

**Issue by HankerSia** [ARISE-Initiative/robosuite#134]
I load a object using the following code:
from robosuite.models.objects.objects import MujocoXMLObject
seat_chair_model = MujocoXMLObject("/home/kai/robosuite/robosuite/models/assets/objects/seat_chair.xml")
world.merge(seat_chair_model)

But, it looks very big in mujoco world. The cotent of the xml file is as shown in the following:
![Screenshot from 2020-12-03 17-29-26](https://user-images.githubusercontent.com/32951817/100990854-5523c300-358d-11eb-8eaa-ab9982ee73a5.png)

Can anyone give me some advice, Thank you very much!

**Comment by cremebrule** [comment]
Hi @HankerSia ,

You can set the scale of your mesh object by setting the `scale` attribute in the corresponding `<mesh ... />` tag. Please see [this reference](http://www.mujoco.org/book/XMLreference.html#mesh) for exact details.

Closing this issue for now, feel free to re-open it if you continue to have problems!

**Comment by HankerSia** [comment]
> Hi @HankerSia ,
> 
> You can set the scale of your mesh object by setting the `scale` attribute in the corresponding `<mesh ... />` tag. Please see [this reference](http://www.mujoco.org/book/XMLreference.html#mesh) for exact details.
> 
> Closing this issue for now, feel free to re-open it if you continue to have problems!

Yes, "scale" had been used for adjust the size of the model. Thanks. Another problems, can you give me a demo of grasping the object loaded by xml files, or some reference code demo. Thank you in advance!

**Comment by cremebrule** [comment]
I assume this is the same question as the new issue you posted, so I'll answer there.

**Comment by SuryaPratapSingh37** [comment]
Hi @HankerSia,                                                                                                                                                                       

Actually, I was loading an object into the robosuite environment using the following code:

![code](https://user-images.githubusercontent.com/70885700/151697258-0a67b411-4619-4bbb-852d-6373719ebf2a.jpg)



As a result, I do see the object in the environment but it doesn’t seem to be a free body, since it is suspended in space and not experiencing any gravity, even though both the collision and visual mesh are in sync, as can be seen in the attached picture. 
![robosuite_environment](https://user-images.githubusercontent.com/70885700/151697451-334c3df7-e960-47b6-bc88-dd479f66c0bb.jpg)
Secondly, if I provide this MujocoXMLObject position coordinates as if it is sitting on top of a moving BoxObject, which acts as a conveyor, then the MujocoXMLObject doesn’t move with the BoxObject and remains stick to its original position in space. Furthermore, if a second BoxObject is placed on top of the moving conveyor, the second BoxObject does move with the conveyor. In fact, the second BoxObject, if it collides with the MujocoXMLObject, is also not able to push the MujocoXMLObject. I find it pretty weird why the MujocoXMLObject doesn’t show the same behaviour like a BoxObject. So can you please help me fix these issues? I'm also attaching the MujocoXMLObject's collision and visual xml files.
![canobject](https://user-images.githubusercontent.com/70885700/151697463-e37f6d77-0ea9-4931-9a43-a14c6c051318.jpg)
![canvisualobject](https://user-images.githubusercontent.com/70885700/151697475-ac2c1b75-10e0-492b-9f92-692e5707a746.jpg)

Thanks in advance
