### ISSUE TITLE
Keeping the last state in demonstration episode

### ISSUE THREAD

**Issue by zhuyifengzju** [ARISE-Initiative/robosuite#177]
It seems that the example script in collecting demonstration deletes the last state of an episode:
https://github.com/ARISE-Initiative/robosuite/blob/a18f1a79a4baa612c43917efd13ff299ff19e7ca/robosuite/scripts/collect_human_demonstrations.py#L143

Shouldn't we keep the last state so that we keep the goal state of an episode? Or save it in a different field?

**Comment by amandlek** [comment]
We did this to make it so that the states and actions are the same length. This isn't an issue since for collecting human demos, we have a "hold" for keeping the last few success states (see [here](https://github.com/ARISE-Initiative/robosuite/blob/a18f1a79a4baa612c43917efd13ff299ff19e7ca/robosuite/scripts/collect_human_demonstrations.py#L73)).
