### ISSUE TITLE
How to disable collision checks?

### ISSUE THREAD

**Issue by SuryaPratapSingh37** [ARISE-Initiative/robosuite#237]
I am trying to attach a custom made gripper(similar to that shown in the figure) to the UR5e arm in robosuite but I feel there are collisions between the gripper and the arm making the arm make weird movements. The same weird behavior is not seen if there is an offset(greater than 3-4 cm) between the arm and gripper. So is there any way by which I can permanently disable collision checks between the arm and the gripper? Similarly, can i disable collision checks between the gripper and the conveyor belt since the gripper tries to push itself away from the conveyor belt when it goes pretty close to the conveyor belt which I guess is again because of collisions?
![robosuite forum1 (1)](https://user-images.githubusercontent.com/70885700/123712944-f909ee80-d890-11eb-8c19-91c1cde114b0.png)

**Comment by cremebrule** [comment]
Hi @SuryaPratapSingh37 ,

You can filter specific collisions by setting elements' `condim` and `conaffinity`, see HERE.

I would recommend against this, since you would have to manually hardcode values in the XMLs that are loaded (or create a new robot arm class with an edited XML file to specifically use with your custom gripper).

Instead, it sounds like your custom gripper is offset incorrectly with respect to the arm. You can toggle viewing the collision geoms by pressing `0` while viewing the `MjViewer` rendered screen at runtime, and toggle the visual geoms by pressing `1`. If it turns out your custom gripper has collision geoms overlapping with the arm, you can set the offset so that they're no longer in collision, e.g. [HERE](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/models/assets/grippers/wiping_gripper.xml#L3) (this is for the Wiping Gripper, used as an example).

**Comment by SuryaPratapSingh37** [comment]
Hi @cremebrule ,                                                                                                                                                                                         

Thank you for your reply, your suggestion about viewing the collision geoms was helpful since my custom gripper collision geom is indeed overlapping with the arm. 

Secondly, out of curiosity can you please also send some example for suppressing the pair of collisions using 'condim' and 'conaffinity' in the arm and gripper XMLs.
