### ISSUE TITLE
Robot model precision

### ISSUE THREAD

**Issue by Fitz13009** [ARISE-Initiative/robosuite#239]
Dear developers in Stanford,

hi, I have a question regarding to the robot model precision. Our research group is developing different controllers for Franka Robot in simulation, but we suffer a lot due to the lack of precision in robot dynamics model and thus the performance is bad. I would like to ask where did you get the robot model, like mass, inertia or did you optimize them on your own?

Thanks in advance,

Best,
Ge Li

**Comment by roberto-martinmartin** [comment]
Hi Ge Li,

sorry for the late response. I don't think our model of the dynamics is very accurate. It is in fact even more simple than what you can find in the official Franka repository as computed based on the CAD models (https://github.com/frankaemika/franka_ros/blob/develop/franka_description/robots/panda_gazebo.xacro). It is fine in our projects because 1) we subtract the effect of the dynamics by using the OSC formalism, and 2) our tasks are quasi-static, not very dynamics-sensitive, e.g., we are not trying to bat a ball or joggle objects.

In the experiments we have done in sim2real, our real-world controller is the same as in simulation, it is just that the dynamics (the mass matrix) is obtained accurately at each robot pose using the Franka library instead of using the dynamics model we use in simulation. AFAIK, Franka does not provide the full dynamics model, only the API to query the mass matrix at each robot pose, which is what we use.

If you obtain a more accurate dynamics model, we would be happy to incorporate it for others to get access to it.

Thanks!
