### ISSUE TITLE
the use of lambda in OSC controller

### ISSUE THREAD

**Issue by shirkozlovsky** [ARISE-Initiative/robosuite#248]
in the OSC controller, you used lambda matrices ((J * M^-1 * J^T)^-1)) before calculating the torques  (J.T*lambda*F). 
I tried to run it without the lambda (the classic torque's calculation: torques = J.T*F) and it works fine. so I don't fully understand the use of lambda. or in which cases I need to use it and which I can skip it.  (for example - do I need to use it in every controller the works in cartesian space or only in the OSC controller?)

thank you

**Comment by roberto-martinmartin** [comment]
Hi,
J^T*F is the general equivalence between wrenches in Cartesian space at the task frame (F) and the corresponding torques in the joints of the robot (tau). The question is what wrench we are commanding and why. In OSC, we compute a wrench that would cause an acceleration that, in turn, minimizes the pose error, the difference between the desired and current pose of the task frame. We multiply by lambda to decouple the rotational and linear part, i.e., to avoid that minimizing the error in orientation causes an error in position and vice-versa. With a closed-loop controller without lambda, the effect may be masked because the error introduced by the lack of the decoupling will be counteracted by the controller in the next step, but it is introducing an unnecessary disturbance. An example that illustrates this can be obtained by taking at each step the current orientation as desired orientation and only compensating for the position, effectively doing only position control: without lambda, the orientation will rapidly drift from the initial orientation, while with lambda, the deviation should be much smaller (theoretically zero) even if we do not actively control to the initial orientation.

One case you don't want to use lambda is when you actually know the exact force in Cartesian space you want to cause, e.g., when you are setting a direct force controller. When controlling poses with forces that will minimize the error, you should use lambda for best and more accurate results.

For more details, I recommend reviewing a good book on robot control or the wonderful original publication from Oussama Khatib: "A unified approach for motion and force control of robot manipulators: The operational space formulation", 1986.
