### ISSUE TITLE
Hiding coordinate system

### ISSUE THREAD

**Issue by danielstankw** [ARISE-Initiative/robosuite#322]
Hi,
When I visualise the simulation and press E I am able to see reference frames. 
How can I disable certain frames from being visible? 
I want to see coordinate frames but I am not interested of seeing them for all the joints. 

Also they are massive. Is there a place I can change their size? 

![image](https://user-images.githubusercontent.com/72759092/166426311-207e6a1a-abf7-4b5c-a6a6-0177960f8ebd.png)

**Comment by danielstankw** [comment]
@cremebrule @roberto-martinmartin

**Comment by danielstankw** [comment]
Anyone?

**Comment by cremebrule** [comment]
Hi @danielstankw ,

(Reposting the response from slack): I think this is a native mujoco visualization functionality that we don't have control over, IIRC.

You might have to look into the low-level C++ code in order to directly modify how the mujoco renderer handles visualizing the frames.

Closing this issue for now, feel free to reopen or start a new issue if you continue to run into issues.
