### ISSUE TITLE
Stereoscopic rendering

### ISSUE THREAD

**Issue by kxgao** [ARISE-Initiative/robosuite#356]
Hello, I'm using the MuJoCo renderer to obtain RGBD images via the Observable class. Are the images constructed using stereoscopic rendering, and is there a way to toggle this setting? Thank you.

**Comment by SteveHan-233** [comment]
I assume that you know how to render stereoscopic images through Mujoco (here's [the documentation](https://mujoco.readthedocs.io/en/latest/APIreference.html?highlight=stereo#mjtstereo)). Now, we just have to toggle this setting in Robosuite. Since Robosuite currently uses Mujocopy to interface with Mujoco, you can reach this setting by something like this: 
```
    viewer = mujoco_py.MjViewer(sim)
    viewer.scn.stereo = 2
```
Let me know if you have any more questions
