### ISSUE TITLE
Clipping issue

### ISSUE THREAD

**Issue by Vivi0928** [ARISE-Initiative/robosuite#482]
I encountered a clipping issue while using simulation. For example, when a cube is dropped in free fall onto a table, if the drop height is too high, the cube will pass straight through the table.

https://github.com/ARISE-Initiative/robosuite/assets/127675505/731ec5f4-5fa7-4692-936f-6c11cc53533c

**Comment by kevin-thankyou-lin** [comment]
Ah yes - this is due to details for the underlying physics simulator ([mujoco](https://mujoco.readthedocs.io/en/stable/computation/index.html#physical-realism-and-soft-contacts)) and how it performs physics. You can read the docs I linked for more detail; but I think w/ the default configs, this is expected --- one way to resolve is to just not drop it from super high; another is to decrease physics timestep size, but w/ enough speed it'll go right through. Closing for now!
